version: '3'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  pgsql_dev:
    image: postgres:alpine
    ports:
      - '5228:5432'
    container_name: 'pgsql_dev'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: finad
      POSTGRES_PASSWORD: finad!2022

  pgsql_dev_shadow:
    image: postgres:alpine
    ports:
      - '5227:5432'
    container_name: 'pgsql_dev_shadow'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: finad
      POSTGRES_PASSWORD: finad!2022

  pgsql_test:
    image: postgres:alpine
    ports:
      - '5111:5432'
    container_name: 'pgsql_test'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: finad
      POSTGRES_PASSWORD: finad!2022

  pgsql_test_shadow:
    image: postgres:alpine
    ports:
      - '5110:5432'
    container_name: 'pgsql_test_shadow'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/pgdata
    environment:
      POSTGRES_USER: finad
      POSTGRES_PASSWORD: finad!2022

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data:
